### ISSUE TITLE
compiling or calculation issue

### ISSUE THREAD

**Issue by jiagu999** [aradi/SCPC-Method#5] opened 2022-04-01 07:00 UTC
Hello :

While trying the SCPC calculation of V_Cl in slab NaCl in VASP.6.2.0, the following error is generated: 

{
 the WAVECAR file was read successfully
 charge-density read from file: wz-GaN
 magnetization density read from file 1
 entering main loop
       N       E                     dE             d eps       ncg     rms          rms(c)
[c12:128095:0:128095] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
==== backtrace (tid: 128095) ====
 0 0x0000000000050a75 ucs_debug_print_backtrace()  ???:0
 1 0x0000000001cf44c8 dl_mg_convergence_params_mp_dl_mg_set_conv_params_()  ???:0
 2 0x0000000001cd64c0 dl_mg_mp_dl_mg_solver_poisson_()  ???:0
 3 0x00000000009bf806 scpc_mp_scpc_mgsolver_()  ???:0
 4 0x00000000009b7eae scpc_mp_scpc_build_correction_()  ???:0
 5 0x00000000009a9bc2 scpc_mp_scpc_apply_()  ???:0
 6 0x00000000009d9893 pot_mp_potlok_()  ???:0
 7 0x0000000000f9cf97 elmin_()  ???:0
 8 0x0000000001ac0d6d vamp_IP_electronic_optimization_()  main.f90:0
 9 0x0000000001a9ac8e MAIN__()  ???:0
10 0x00000000004124e2 main()  ???:0
11 0x0000000000022505 __libc_start_main()  ???:0
12 0x00000000004123e9 _start()  ???:0
=================================
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
vasp_std           0000000001D73C9A  Unknown               Unknown  Unknown
libpthread-2.17.s  00007F3D24C7D5F0  Unknown               Unknown  Unknown
vasp_std           0000000001CF44C8  Unknown               Unknown  Unknown
vasp_std           0000000001CD64C0  Unknown               Unknown  Unknown
vasp_std           00000000009BF806  Unknown               Unknown  Unknown
vasp_std           00000000009B7EAE  Unknown               Unknown  Unknown
vasp_std           00000000009A9BC2  Unknown               Unknown  Unknown
vasp_std           00000000009D9893  Unknown               Unknown  Unknown
vasp_std           0000000000F9CF97  Unknown               Unknown  Unknown
vasp_std           0000000001AC0D6D  Unknown               Unknown  Unknown
vasp_std           0000000001A9AC8E  Unknown               Unknown  Unknown
vasp_std           00000000004124E2  Unknown               Unknown  Unknown
libc-2.17.so       00007F3D245C0505  __libc_start_main     Unknown  Unknown
vasp_std           00000000004123E9  Unknown               Unknown  Unknown

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 1 PID 128096 RUNNING AT c12
...
}

I compiled VASP.6.2.0 with SCPC following this way:
{
       -- check the makefile.include to add the right path
          for the external libraries for the Poisson and Isolate potential
          solver

       -- edit the variables at makefile.include to point your own
          installation

          #SCPC METHOD
          LIBEXT     = /someplace/libext
          DLMGROOT   = $(LIBEXT)/dl_mg_2.0.2
          PSPFFTROOT = $(LIBEXT)/pspfft-1.0
          INCS      +=-I$(DLMGROOT)/lib
          INCS      +=-I$(PSPFFTROOT)/include
          LLIBS     +=-Wl,--start-group $(DLMGROOT)/lib/libdlmg.a -Wl,--end-group
          LLIBS     +=-Wl,--start-group $(PSPFFTROOT)/lib/libpspfft.a -Wl,--end-group
          #SCPC METHOD

      (b.1) For VASP-6.2.0, it is necessary to add -DSCPC to the CPP_OPTIONS in the
            beginning of the makefile.include 
}

And the INCAR file is follow
{
NCORE = 6

EDIFF = 1E-5
NELM= 40
NELMIN=6
LWAVE  = F ; write WAVECAR
LCHARG = F ; write CHGCAR

ISTART = 1 ; WAVECAR begin 0-from scratch 1-restart
ICHARG = 1 ; charge guess (2) orbital superposition   (1) read charge     (11) non-scf

EDIFFG = -1E-2
ENCUT = 520
GGA = PS
IBRION = 2; POTIM=0.3
NSW = 0
ISIF = 2

ISPIN = 2
NELECT = 440

ISMEAR = 0; SIGMA = 0.05

LREAL = Auto
LORBIT = 11
LVHAR=.TRUE.

SCPC {
    USE   = T
    IN    = 1
    QTOT  = 1.00
    ZLOW  = 0.333
    ZHIG  = 0.586
    DIEL  = 2.46
    BROAD = 0.40
     }
}

And the reference CHGCAR and LOCPOT come from the nutral defect calculation. I don't know where this wrong results from.
Thank you for your help, sincerely

**Comment by isobestico** [comment] 2022-04-01 07:17
Are you sure you are copying things from the right place?
In the beginning of your error report to me says:

**the WAVECAR file was read successfully
charge-density read from file: wz-GaN**

If you doing Vcl calculation while it says that the charge-density read from a file 
name wz-GaN ?

**Comment by jiagu999** [comment] 2022-04-01 07:33
The CHGCAR are named wrong, but it doesn't matter.

{
wz-GaN
   1.00000000000000
    11.207726    0.000000    0.000000
     0.000000   11.207726    0.000000
     0.000000    0.000000   33.207726
   Na   Cl
    32    31
Direct
  0.000000  0.000000  0.333077
  0.000000  0.000000  0.500829
  0.000000  0.500000  0.333006
  0.000000  0.500000  0.500690
  0.500000  0.000000  0.333006
  0.500000  0.000000  0.500690
  0.500000  0.500000  0.332621
  0.500000  0.500000  0.499065
  0.249991  0.249991  0.333068
  0.250039  0.250039  0.500945
  0.249991  0.750009  0.333068
  0.250039  0.749961  0.500945
  0.750009  0.249991  0.333068
  0.749961  0.250039  0.500945
  0.750009  0.750009  0.333068
  0.749961  0.749961  0.500945
  0.249906  0.000000  0.414770
  0.249416  0.000000  0.582570
  0.249627  0.500000  0.414648
  0.247016  0.500000  0.583141
  0.750094  0.000000  0.414770
  0.750584  0.000000  0.582570
  0.750373  0.500000  0.414648

}

**Comment by isobestico** [comment] 2022-04-01 07:42
OK, Could you please send us your full POSCAR?

**Comment by jiagu999** [comment] 2022-04-01 07:48
Thank you!
{
Na1 Cl1                                 
   1.00000000000000     
    11.2077264785999997    0.0000000000000000    0.0000000000000000
     0.0000000000000000   11.2077264785999997    0.0000000000000000
     0.0000000000000000    0.0000000000000000   33.2077255248999990
   Na   Cl
    32    31
Direct
  0.0000000000000000 -0.0000000000000000  0.3330766142183409
  0.0000000000000000 -0.0000000000000000  0.5008290948325371
  0.0000000000000000  0.5000000000000000  0.3330058475899293
  0.0000000000000000  0.5000000000000000  0.5006901110436328
  0.5000000000000000 -0.0000000000000000  0.3330058475899293
  0.5000000000000000 -0.0000000000000000  0.5006901110436328
  0.5000000000000000  0.5000000000000000  0.3326213199624504
  0.5000000000000000  0.5000000000000000  0.4990654163440550
  0.2499911242588223  0.2499911242588223  0.3330682199473684
  0.2500389866582461  0.2500389866582461  0.5009451237247760
  0.2499911242588223  0.7500088757411776  0.3330682199473684
  0.2500389866582461  0.7499610133417539  0.5009451237247760
  0.7500088757411776  0.2499911242588223  0.3330682199473684
  0.7499610133417539  0.2500389866582461  0.5009451237247760
  0.7500088757411776  0.7500088757411776  0.3330682199473684
  0.7499610133417539  0.7499610133417539  0.5009451237247760
  0.2499060304442583 -0.0000000000000000  0.4147701149302737
  0.2494159369288308 -0.0000000000000000  0.5825700833500855
  0.2496273893117400  0.5000000000000000  0.4146479933463040
  0.2470163410374749  0.5000000000000000  0.5831409141402318
  0.7500939695557418 -0.0000000000000000  0.4147701149302737
  0.7505840630711692 -0.0000000000000000  0.5825700833500855
  0.7503726106882601  0.5000000000000000  0.4146479933463040
  0.7529836589625251  0.5000000000000000  0.5831409141402318
  0.0000000000000000  0.2499060304442583  0.4147701149302737
  0.0000000000000000  0.2494159369288308  0.5825700833500855
  0.0000000000000000  0.7500939695557418  0.4147701149302737
  0.0000000000000000  0.7505840630711692  0.5825700833500855
  0.5000000000000000  0.2496273893117400  0.4146479933463040
  0.5000000000000000  0.2470163410374749  0.5831409141402318
  0.5000000000000000  0.7503726106882601  0.4146479933463040
  0.5000000000000000  0.7529836589625251  0.5831409141402318
  0.2500594613141343  0.2500594613141343  0.4160486588429698
  0.2499882690452323  0.2499882690452323  0.5858581174401047
  0.2500594613141343  0.7499405386858659  0.4160486588429698
  0.2499882690452323  0.7500117309547677  0.5858581174401047
  0.7499405386858659  0.2500594613141343  0.4160486588429698
  0.7500117309547677  0.2499882690452323  0.5858581174401047
  0.7499405386858659  0.7499405386858659  0.4160486588429698
  0.7500117309547677  0.7500117309547677  0.5858581174401047
  0.0000000000000000 -0.0000000000000000  0.4160094334102339
  0.0000000000000000 -0.0000000000000000  0.5857701568924275
  0.0000000000000000  0.5000000000000000  0.4159652835720914
  0.0000000000000000  0.5000000000000000  0.5857392901968069
  0.5000000000000000 -0.0000000000000000  0.4159652835720914
  0.5000000000000000 -0.0000000000000000  0.5857392901968069
  0.5000000000000000  0.5000000000000000  0.4156113899396827
  0.0000000000000000  0.2499916597822217  0.3300564827474544
  0.0000000000000000  0.2500745717640377  0.4994344963071497
  0.0000000000000000  0.7500083402177783  0.3300564827474544
  0.0000000000000000  0.7499254282359623  0.4994344963071497
  0.5000000000000000  0.2499419250529168  0.3300080048794398
  0.5000000000000000  0.2501607749414532  0.4995368620436710
  0.5000000000000000  0.7500580749470832  0.3300080048794398
  0.5000000000000000  0.7498392250585468  0.4995368620436710
  0.2499916597822217 -0.0000000000000000  0.3300564827474544
  0.2500745717640377 -0.0000000000000000  0.4994344963071497
  0.2499419250529168  0.5000000000000000  0.3300080048794398
  0.2501607749414532  0.5000000000000000  0.4995368620436710
  0.7500083402177783 -0.0000000000000000  0.3300564827474544
  0.7499254282359623 -0.0000000000000000  0.4994344963071497
  0.7500580749470832  0.5000000000000000  0.3300080048794398
  0.7498392250585468  0.5000000000000000  0.4995368620436710
}

**Comment by isobestico** [comment] 2022-04-01 08:01
thank you, I will try to reproduce your error in my local compilation of VASP-6.2.1. 
The backtrace of your error report says something went wrongly with the Poisson 
Solver. Maybe your DL_MG compilation is not right!

You should compile everything using exactly the same compiler (intel or gnu!), I mean 
those external libraries needed by SCPC inside VASP and VASP should be compiled using 
exactly the same compiler.

Anyhow, I will check and come to you soon

**Comment by jiagu999** [comment] 2022-04-01 08:07
thanks, I will check that you mentioned.

**Comment by jiagu999** [comment] 2022-04-01 08:19
The DLMG version I compiled is v3.1.0, dose it matter?
{
OBJECTS    = fftmpiw.o fftmpi_map.o fft3dlib.o fftw3d.o

DLMGROOT = /share/softwares/packages/dlmg-v3.1.0-rc.17
PSPFFTROOT = /usr/local/pspfft/1.0

INCS       =-I$(MKLROOT)/include/fftw
INCS       +=-I$(DLMGROOT)/lib
INCS       +=-I$(PSPFFTROOT)/include

LLIBS      = $(SCALAPACK) $(LAPACK) $(BLAS)
LLIBS      += -Wl,--start-group $(PSPFFTROOT)/lib/libpspfft.a -Wl,--end-group
LLIBS      += -Wl,--start-group $(DLMGROOT)/lib/libdlmg.a -Wl,--end-group


}

**Comment by isobestico** [comment] 2022-04-01 09:16
I used your POSCAR and some of your configurations (GGA and POTCAR). 
Everything ran fine for me up to now. May I ask you to rerun the example I am copying here with your installation?

However, I have a comment on your SCPC input, please the interface should not be putted in the atomic boundaries as you did. 

We are suggesting shifting it away around 1-1.5 Angstroms. So in my example copied here you will notice that 

    ZLOW  = 0.29
    ZHIG    = 0.62

[issue_slab_nacl_vasp621.zip](https://github.com/aradi/SCPC-Method/files/8396322/issue_slab_nacl_vasp621.zip)

In each folder (charge, neutral, and scpc) there is a << CopyFile.bash >> script to copy the necessary file. You must run this script before vasp execution to guarantee you are copying the right files. Also, drop your POTCAR file into the template directory. 

I also copied all my OUTCAR, vasp.out and SCPCOUT file for conference.

**Comment by jiagu999** [comment] 2022-04-01 09:49
I have rerun the example as you adviced, there is still the same wrong.  So, there should be some wrong with my compilation. 

The .log file shows:
{ the WAVECAR file was read successfully
 initial charge from wavefunction
 entering main loop
       N       E                     dE             d eps       ncg     rms          rms(c)
[c12:156641:0:156641] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
==== backtrace (tid: 156641) ====
 0 0x0000000000050a75 ucs_debug_print_backtrace()  ???:0
 1 0x0000000001cf44c8 dl_mg_convergence_params_mp_dl_mg_set_conv_params_()  ???:0
 2 0x0000000001cd64c0 dl_mg_mp_dl_mg_solver_poisson_()  ???:0
 3 0x00000000009bf806 scpc_mp_scpc_mgsolver_()  ???:0
 4 0x00000000009b7eae scpc_mp_scpc_build_correction_()  ???:0
 5 0x00000000009a9bc2 scpc_mp_scpc_apply_()  ???:0
 6 0x00000000009d9893 pot_mp_potlok_()  ???:0
 7 0x0000000000f9cf97 elmin_()  ???:0
 8 0x0000000001ac0d6d vamp_IP_electronic_optimization_()  main.f90:0
 9 0x0000000001a9ac8e MAIN__()  ???:0
10 0x00000000004124e2 main()  ???:0
11 0x0000000000022505 __libc_start_main()  ???:0
12 0x00000000004123e9 _start()  ???:0
=================================
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
vasp_std           0000000001D73C9A  Unknown               Unknown  Unknown
libpthread-2.17.s  00007FCD264515F0  Unknown               Unknown  Unknown
vasp_std           0000000001CF44C8  Unknown               Unknown  Unknown
vasp_std           0000000001CD64C0  Unknown               Unknown  Unknown
vasp_std           00000000009BF806  Unknown               Unknown  Unknown
vasp_std           00000000009B7EAE  Unknown               Unknown  Unknown
vasp_std           00000000009A9BC2  Unknown               Unknown  Unknown
vasp_std           00000000009D9893  Unknown               Unknown  Unknown
vasp_std           0000000000F9CF97  Unknown               Unknown  Unknown
vasp_std           0000000001AC0D6D  Unknown               Unknown  Unknown
vasp_std           0000000001A9AC8E  Unknown               Unknown  Unknown
vasp_std           00000000004124E2  Unknown               Unknown  Unknown
libc-2.17.so       00007FCD25D94505  __libc_start_main     Unknown  Unknown
vasp_std           00000000004123E9  Unknown               Unknown  Unknown
}

Dose the version of DLMG result for it? I can't get the v2.1.4 DL_MG from the official website.

**Comment by isobestico** [comment] 2022-04-01 10:12
No, I used a new version, but I will try to recompile everything in another cluster, with newer intel and DL_MG 3.X. I am still investigating if there is some issue/dependence with the DL_MG new version, I have just cloned the DL_MG library. I will try with a new version and let you know

**Comment by jiagu999** [comment] 2022-04-01 10:24
Thanks for your help, hope to try your compilation process.

**Comment by isobestico** [comment] 2022-04-01 14:06
I recompiled everything with intel 2020 and openmpi 4.0 and I was not able to reproduce your issue. I used the most recent DL_MG cloned from their repository. Also, I tested with the vasp_std (KPTS=4x4x1) and vasp_gam

https://bitbucket.org/dlmgteam/dl_mg_code_public/src/master/

 DL_MG 3.0.0 (13/06/2021)
 << Compiled with MPI >>

I think you should double-check your compilation (VASP and libraries). Try to clone again using the link above 
because the most recent version I tested was 3.0.0.  Do not use dev. or pre-release versions.  

Hence, I will close this issue.

**Closed by isobestico** 2022-04-01 14:06 UTC

**Comment by isobestico** [comment] 2022-04-01 14:32
The version dlmg-v3.1.0-rc.17.tar.gz indeed is giving an error, I only found now that you have downloaded from the download repository, they probably chanced something very substantial. Please use 

git clone https://bitbucket.org/dlmgteam/dl_mg_code_public.git

I still leave this issue closed because it is not a problem with SCPC

**Comment by jiagu999** [comment] 2022-04-01 14:46
Thank you so much for your help for so long, I'll double-check, sincerely

**Comment by jiagu999** [comment] 2022-04-02 05:03
I have solved this problem after changing the DL_MG to v3.0.0, thanks again
